# encoding: utf-8
src=<<EOS
エースコックベトナム社 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201705-acecook.html			〇					〇					〇														〇										〇																					〇	〇				〇	〇							〇	〇																		〇				〇				〇												〇	〇	〇									○								○												○						○			○			○				○	○														○	○	○			○	○							〇																									○	○																
株式会社 島津製作所 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201705-shimadzu-corporation.html			〇					〇		〇																	〇		〇																													〇		〇										〇																			〇					〇			〇												〇										○									○													○		○										○					○																			○	○		○								○																				○			○																
株式会社 静岡新聞社 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201705-shizuoka-shimbun.html			〇					〇												〇						〇		〇																																	〇															〇																												〇					〇																○							○					○				○				○															○										○								○		○										○																				○	○																
東京都建設局 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201705-tokyo-construction-bureau.html			〇					〇																								〇	〇	〇																												〇																							〇																								〇																○					○								○						○						○			○	○				○																					○						○																		〇						○																		
独立行政法人 水資源機構　琵琶湖開発総合管理所 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201704-japan-water-agency.html			〇					〇			〇																		〇			〇		〇	〇						〇																					〇															〇				〇																		〇										〇																○					○							○		○		○		○	○																○				○																○										○																					○																
メタウォーター株式会社 様				〇								○					○				○					○		○		○		○	○	○	○										○																																	○			○	○																○	○											〇											○										○								○			○																								○			○						○					○									○																				○	○	○																	
熊本県高森町役場 様／福岡県直方市役所 様				〇								○				○																○	○	○												○																																								○													○						○					〇																○										○		○				○						○						○					○		○																		○		○								○																						○	○																
韓国金融決済院　様	http://www.fujitsu.com/jp/about/resources/case-studies/cs-201707-yessign.html																																																																																																																													○										○																																																																																												
LOTTE CARD 様	http://www.fujitsu.com/jp/about/resources/case-studies/cs-201707-lottecard.html																																																																																																																													○										○																																																																																												
スタンレー電気　様	公開予定																																																																																																																									○									○																																																																																																	
岐阜大学　様	9月公開予定																																																																																																																													○					○																																																																																																	
																																																																																																																																																																																																																																				
製造ラインを「丸ごと自動化」した富士通周辺機	http://www.fujitsu.com//jp/innovation/digital/manufacturing/dl-contents/2017/topics-01/			○			○				○																			○										○																															○																																																							○						○																																																																																																
AI画像認識技術	http://www.fujitsu.com/jp/innovation/digital/manufacturing/dl-contents/2017/topics-02/index.html						○				○											○																			○																																																																																		○								○																																																																																																	
山梨工場	http://www.fujitsu.com/jp/innovation/digital/manufacturing/dl-contents/2017/case-study-01/index.html			○			○				○																			○																																									○																																																			○											○																																																																																															
(CX360)パーソナルマーケティングの理想と現実のギャップを埋める秘訣とは？	http://www.fujitsu.com/jp/innovation/digital/digitalmarketing/dl-contents/2017/topics-01/index.html						○								○																																																																																																																																																																																																																					
(XDP)企業の競争力を高めるマーケティングのカギは大量に収集されたデータにあった	http://www.fujitsu.com/jp/innovation/digital/digitalmarketing/dl-contents/2017/topics-02/index.html						○								○																																																																																																																																																																																																																					
 (市場トレンド)BtoC企業で先行するデジタルマーケティング、これから取り組むBtoB企業が押さえておきたいポイントとは？	http://www.fujitsu.com/jp/innovation/digital/digitalmarketing/dl-contents/2017/market-trend-01/index.html						○								○																																																																																																																																																																																																																					
(CX最大化）“顔の見えない顧客”を捉え、カスタマーエクスペリエンスを向上させるには？	http://www.fujitsu.com/jp/innovation/digital/digitalmarketing/dl-contents/2017/topics-03/index.html						○								○																																																																																																																																																																																																																					
(SEが語る成功の秘訣）3つの事例に学ぶ デジタルマーケティングを始めるために情シス部門がおさえるべき勘所							○								○																																																																																																																																																																																																																					
現場作業員が安心して働ける、IoTを活用した作業環境作りとは	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/topics-01/index.html						○											○			○									○						○																																																																																																																																																																																																
現場作業員の状態を把握。今すぐ始められる現場と企業をつなぐICT技術とは？	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/market-trend-01/index.html						○											○			○									○						○																																																																																																																																																																																																
気軽に導入できる「危険ゼロ」安全マネジメントの仕組みとは	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/topics-03/index.html						○											○																																																																																																																																																																																																																		
IoTで実現！小規模、低コストで転倒・転落事故を見逃さない方法とは？	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/topics-02/index.html						○											○			○									○						○																																																																																																																																																																																																
さらに進む介護施設の重労働と人材不足。見守りの仕組みで労働環境を改善	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/topics-04/index.html						○											○			○									○																																																																																																																																																																																																						
「決め手はIoTと音」高齢者見守りサービスは次のステップへ	http://www.fujitsu.com/jp/innovation/digital/life/dl-contents/2017/topics-05/index.html						○											○			○									○																																																																																																																																																																																																						
金融サービスを革新するFintech カギはベンチャーやICTベンダーとの共創	http://www.fujitsu.com/jp/innovation/digital/fintech/dl-contents/2017/topics-01/index.html						○												○		○											○																																																																																																																																																																																																				
潜在ニーズを引き出す人工知能（AI）を使った顧客サービスとは？（チャットボット）	http://www.fujitsu.com/jp/innovation/digital/fintech/dl-contents/2017/topics-02/index.html						○												○		○	○										○									○																																																																																																																																																																																											
進化するFintechと次々生まれる新サービスとは	http://www.fujitsu.com/jp/innovation/digital/fintech/dl-contents/2017/market-trend-01/index.html						○												○																																																																																																																																																																																																																	
Fintech、次の方向性	公開準備中						○												○																																																																																																																																																																																																																	
【第1回】デジタルシフトを支えるこれからのシステムの方向性 	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/topics-01/index.html						○														○					○						○																																																																																																																																																																																																				
【第2回】グローバル化に求められるICTの対応策	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/topics-02/index.html						○														○					○						○																																																																																																																																																																																																				
【第3回】富士通の全社システムクラウド化への挑戦	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/case-study-01/index.html						○														○					○						○																																																																																																																																																																																																				
【第4回】基幹系システムのクラウド移行の最適解	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/topics-03/index.html						○														○					○						○																																																																																																																																																																																																				
【第5回】デジタルビジネスの早期立上げに向けた有効策	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/topics-04/index.html						○														○					○						○																																																																																																																																																																																																				
【第6回】これからのクラウド連携の考え方	http://www.fujitsu.com/jp/innovation/hybrid-it/dl-contents/2017/topics-05/index.html						○														○					○						○																																																																																																																																																																																																				
つまづく原因は5つの「ない」？	http://www.fujitsu.com/jp/innovation/workstyle/dl-contents/2017/topics-02/						○																				○							○													○																																																																																																																																																																																					
ウェアラブル端末＆スマートデバイス、「肌身のICT」の使い方	http://www.fujitsu.com/jp/innovation/workstyle/dl-contents/2017/topics-03/						○																				○							○		○											○																																																																																																																																																																																					
社員16万人の「知」を共有し、働き方改革を実現させた仕組みとは？	http://www.fujitsu.com/jp/innovation/workstyle/dl-contents/2017/case-study-02/						○																				○																				○																																																																								○										○																																																																																																			
1日100万種超で増殖するマルウェア／セキュリティ対策の考え方を抜本的に変える時がきた	http://www.fujitsu.com/jp/innovation/security/dl-contents/2017/market-trend.html						○																						○																																																																																																																																																																																																							
攻撃者優位は終わった。／サイバー攻撃の全体像を瞬時に可視化する最新技術とは？	http://www.fujitsu.com/jp/innovation/security/dl-contents/2017/case-study-01/index.html						○																						○																																																																																																																																																																																																							
日々100万超で増殖するマルウェア！／AIでサイバー攻撃の被害を食い止めるには	http://www.fujitsu.com/jp/innovation/security/dl-contents/2017/topics-01/index.html						○															○							○												○																																																																																																																																																																																											
1日2000件の標的型サイバー攻撃に立ち向かう具体的なノウハウとは？	http://www.fujitsu.com/jp/innovation/security/dl-contents/2017/case-study-02/index.html						○																						○																																																																																										○										○																																																																																																			
セキュリティ技術者の不足が深刻な課題に社内育成は何から始めるべきか？	http://www.fujitsu.com/jp/innovation/security/dl-contents/2017/case-study-03/index.html						○																						○																																																																																																																																																																																																							
重要インフラをサイバー攻撃から守れ！内部に潜伏し拡散する脅威への対策とは	公開準備中						○																						○																																																																																																																																																																																																							
INESA様ケーススタディ	journal.jp.fujitsu.com/2016/10/31/01/																				○													○																																																																																												○			○																																																																																																			
郡山市	journal.jp.fujitsu.com/2016/08/29/01/																				○																																																																																																									○					○																																																																																																	
南都銀行様事例	journal.jp.fujitsu.com/2016/01/26/01/																				○																																																																																																														○																																																																																																	
静岡新聞社様事例	journal.jp.fujitsu.com/2016/05/23/01/																				○																																																																																																									○							○																																																																																															
旭酒造	journal.jp.fujitsu.com/2014/08/26/01/																				○																																																																																																									○								○																																																																																														
オムロン株式会社様	journal.jp.fujitsu.com/2015/04/20/01/																				○																																																																																																		○（連結）			○							○（連結）																																																																																																			
トヨタ自動車株式会社様	journal.jp.fujitsu.com/2015/04/01/01/																				○													○																																																																																					○										○																																																																																																			
イオンアグリ創造株式会社様	journal.jp.fujitsu.com/2014/11/10/02/																				○																																																																																																									○										○																																																																																												
広島県商工会連合会様	journal.jp.fujitsu.com/2015/10/22/01/																				○																																																																																																									○										○																																																																																												
武蔵野銀行様	journal.jp.fujitsu.com/2016/01/20/01/																				○													○																																																																																								○									○																																																																																																	
社内実践／小山工場	journal.jp.fujitsu.com/2017/04/19/01/																					○																																																																																																	○										○																																																																																																			
サン・カルロス医療研究所様	journal.jp.fujitsu.com/2016/12/09/01/																					○																																																																																																								○										○																																																																																												
社内実践／コールセンター	journal.jp.fujitsu.com/2016/12/08/01/																					○																																																																																																	○										○																																																																																																			
糸島市	journal.jp.fujitsu.com/2016/11/11/01/																					○												○																																																																																												○										○																																																																																												
シンガポール スマート・ネーション	journal.jp.fujitsu.com/2016/10/14/01/																					○																																																																																																								○										○																																																																																												
東ロボ / 国立情報学研究所	journal.jp.fujitsu.com/2016/01/04/01/																					○																																																																																																								○										○																																																																																												
福岡空港ビルディング	journal.jp.fujitsu.com/2015/10/15/01/																					○												○																																																																																												○										○																																																																																												
株式会社ふくおかフィナンシャルグループ 様／iBank マーケティング株式会社 様	www.fujitsu.com/jp/microsite/vision/customerstories/fukuoka-fg-ibank/														○			○														○	○	○																																		○																																										○											○									○																																																																																																		
ズベルバンク（ロシア連邦貯蓄銀行）様	www.fujitsu.com/jp/vision/customerstories/sberbank/																	○											○				○													○																						○																																																○										○		○																																																																																																				
株式会社東京証券取引所 様	www.fujitsu.com/jp/vision/customerstories/tokyo-stock-exchange/											○																○																																										○																																								○														○（連結）									○																																																																																															
カイシャバンク様	www.fujitsu.com/jp/vision/customerstories/caixa-bank/																	○															○																																			○																																											○			○					○										○																																																																																																			
上海儀電(集団) 有限公司(INESA)様	www.fujitsu.com/jp/microsite/vision/customerstories/inesa/										○																○	○																																											○																																									○														○			○																																																																																																			
株式会社巴コーポレーション 様	www.fujitsu.com/jp/microsite/vision/customerstories/tomoe-corporation/										○																						○								○																														○																																							○														○									○																																																																																															
オプテックス 株式会社 様	www.fujitsu.com/jp/microsite/vision/customerstories/optex/																○													○		○	○																																						○																																							○																3億5千万					○（連結）																																																																																																	
HomeServe USA 様	www.fujitsu.com/jp/microsite/vision/customerstories/homeserveusa/											○														○	○																																																									○																											○															○						○																																																																																																
トヨタ自動車株式会社様 活用事例	www.fujitsu.com/jp/vision/customerstories/toyota-motor/										○																	○				○		○				○																																	○																																							○									○									○																																																																																																				
エアバス様	www.fujitsu.com/jp/vision/customerstories/airbus/										○			○																○																																									○																																								○			○					○			○						○																																																																																																				
オムロン株式会社様	www.fujitsu.com/jp/vision/customerstories/omron/										○																○	○						○																																					○																																							○									○（連結）			○							○（連結）																																																																																																			
パナソニック株式会社様	www.fujitsu.com/jp/vision/customerstories/panasonic/														○			○											○		○												○																												○																																							○									○（連結）									○（連結）																																																																																																				
Soitec S.A.様	www.fujitsu.com/jp/vision/customerstories/soitec/										○																					○																																								○																																							○			○												○					○																																																																																																	
Sグループ 様 / ABCペトロール 様	www.fujitsu.com/jp/microsite/vision/customerstories/sgroup-abcpetrol/																	○								○							○					○								○																											○																																						○			○												○			○																																																																																																			
クオール株式会社 様	www.fujitsu.com/jp/microsite/vision/customerstories/qol/																	○														○																																									○																																					○														○							○																																																																																																	
マクドナルド（UK）様	www.fujitsu.com/jp/microsite/vision/customerstories/mcdonalds/											○																	○																																												○																																						○			○												○		○																																																																																																				
オーシャン様	www.fujitsu.com/jp/vision/customerstories/auchan/																	○												○			○																																								○																																						○			○							○							○																																																																																																				
株式会社三越伊勢丹ホールディングス様	www.fujitsu.com/jp/vision/customerstories/isetan-mitsukoshi/														○													○			○																																										○																																					○												○						○																																																																																																				
サンカルロス医療研究所 様	www.fujitsu.com/jp/microsite/vision/customerstories/hospital-clinico-san-carlos/																	○																							○																																						○																																〇			〇												○				○																																																																																																		
オーストラリア首都特別地域保健局（キャンベラ病院）様	www.fujitsu.com/jp/vision/customerstories/canberra-hospital/																	○											○				○																																														○																																○															○										○																																																																																												
東京大学様	www.fujitsu.com/jp/vision/customerstories/university-of-tokyo/																	○										○																																																			○								○																							○																○				○（教員）																																																																																																		
東京大学先端科学技術研究センター様	www.fujitsu.com/jp/vision/customerstories/research-center-university-of-tokyo/																	○										○																																																			○																															○																○							○（教員）																																																																																															
Emory Healthcare様	www.fujitsu.com/jp/vision/customerstories/emory-healthcare/																	○																																																													○																																○			○												○			○																																																																																																			
株式会社スマートアグリカルチャー磐田 様／富士通・オリックス・増田採種場共同事業	www.fujitsu.com/jp/vision/customerstories/iwata-smart-agriculture/															○					○									○		○	○									○	○			○																											○	○												○																								○																○										○																																																																																												
旭酒造株式会社様	www.fujitsu.com/jp/vision/customerstories/asahi-shuzo/															○														○		○	○																																								○																																					○																○								○																																																																																														
イオンアグリ創造株式会社様	www.fujitsu.com/jp/vision/customerstories/aeon-agri-create/															○														○		○	○	○																																							○																																					○																５千万							○																																																																																															
テックショップ様	www.fujitsu.com/jp/vision/customerstories/tech-shop/										○																												○					○	○																																										○																							○																○						○																																																																																																
筑波大学附属小学校様	www.fujitsu.com/jp/vision/customerstories/tsukuba-elementary-school/																	○																												○																																									○																							○																○										○																																																																																												
オーストラリア・ポスト 様	www.fujitsu.com/jp/microsite/vision/customerstories/auspost/																	○																																																																			○																										○															○		○																																																																																																				
リチャードソン警察署 様	www.fujitsu.com/jp/vision/customerstories/richardson-police-department/																	○									○						○																																																					○																									○															○							○																																																																																															
シンガポール科学技術研究庁（A*STAR）様／シンガポールマネジメント大学 様	www.fujitsu.com/jp/vision/customerstories/a-star/																○	○			○							○										○					○																																										○																										○	○														○										○																																																																																												
ジャカルタ州防災局様	www.fujitsu.com/jp/vision/customerstories/bpbd-dki-jakarta/																○																					○																																															○																										○	○														○								○																																																																																														
メタウォーター 株式会社 様（2017）	www.fujitsu.com/jp/microsite/vision/customerstories/metawater/																○															○																																																		○																												○											○（連結）										○																																																																																																	
ポルトガル鉄道 様	www.fujitsu.com/jp/vision/customerstories/comboios-de-portugal/																○											○																																															○																																				○			○												○					○																																																																																																	
スコティッシュ・ウォーター 様	www.fujitsu.com/jp/vision/customerstories/scottish-water/											○																	○																																																					○																													○			○												○					○																																																																																																	
株式会社NTTドコモ様	www.fujitsu.com/jp/vision/customerstories/ntt-docomo/																	○								○																																																		○																																		○										○									○（連結）																																																																																																			
メタウォーター株式会社様（2014）	www.fujitsu.com/jp/vision/customerstories/metawater/																															○																																																		○																												○											○（連結）										○																																																																																																	
［社内事例］ 富士通株式会社	www.fujitsu.com/jp/microsite/vision/customerstories/fujitsu/																									○	○																																																	○																																		○									○									○																																																																																																				
株式会社日経BP 様	www.fujitsu.com/jp/vision/customerstories/nikkei-bp/														○						○										○																																														○			○																														○																4億円						○																																																																																																
三井化学株式会社 様	www.fujitsu.com/jp/vision/customerstories/mitsui-chemicals/														○						○										○																																									○																																						○											○								○																																																																																																			
株式会社スクウェア・エニックス 様	www.fujitsu.com/jp/vision/customerstories/square-enix/																												○																																																○																																	○															○						○（連結）																																																																																																	
株式会社レオパレス21 様	www.fujitsu.com/jp/vision/customerstories/leopalace21/																	○			○							○			○	○											○																																			○																																○												○								○																																																																																																		
株式会社電通様	www.fujitsu.com/jp/vision/customerstories/dentsu/														○													○																																																	○																																	○												○								○																																																																																																		
iHeart Studios様	www.fujitsu.com/jp/vision/customerstories/iheart/																															○																																													○																																		○			○												○							○																																																																																															
Qantas Airways Limited様	www.fujitsu.com/jp/vision/customerstories/qantas-airways/																										○																																																○																																				○															○			○																																																																																																			
EOS



TAB="\t"

KEYWORDS="実装キーワード			記事	事例	製品紹介	プレスリリース	ホワイトペーパー	イベントセミナー	デジタル革新		ものづくり	保守保全	モビリティ	ロジスティクス	デジタルマーケティング	食農業	都市インフラ	職場・暮らし	Fintech		MetaArc	Zinrai				ハイブリッドIT	ワークスタイル変革	ビッグデータ	セキュリティ	IoT	BI	クラウドサービス	モバイルテクノロジ	スマートデバイス	AR	ウェアラブル	ソーシャルメディア	ロケーションインテリジェンス	3Dプリンティング	スマートマシン	AI	技術技能伝承	共創	デザインシンキング	オープンイノベーション	地方創成/地域活性化			モノのインターネット (IoT)	ビッグ・データ	ビジネス・インテリジェンス	クラウド・サービス	モバイル・テクノロジ	ソーシャル・メディア	ロケーション・インテリジェンス	3Dプリンティング	スマートマシン		製造	食品	機械	情報産業通信	官公庁自治体	流通	小売			銀行	保険	証券その他金融サービス	組立製造	プロセス製造	小売	卸売	運輸	通信	メディア	公共公益	医療	情報サービス	建設土木	資源	専門的サービス	個人向けサービス	中央官庁	地方自治体	教育	消費者		生産管理	物流			人事給与	生産販売	受注販売	在庫管理	計画系	実行系	調達系	サポート	営業支援	EC	マーケティング力強化	グループウェア	BI分析	メール	オフィススイート		国内	海外	アジア	ベトナム	ヨーロッパ	ドイツ	グローバル			規模A	規模B	規模C	規模D	規模E	規模F	規模G	規模X		規模1	規模2	規模3	規模4	規模5	規模6	規模7	規模8	規模9		セキュリティ強化	ITコスト削減	システム標準化	技術革新対応	迅速な対応力	適正なIT予算	業務理解力向上	IT要員不足	業務部門連携	IT戦略策定	プロジェクト管理	ベンダー管理	IT投資対効果	グローバルシステム	その他のIT課題		コスト削減	新規顧客獲得	人材育成	営業力強化	顧客サービス強化	生産性向上	人材確保	業務プロセス改善	既存顧客維持	財務体質改善	マーケティング力強化	競争力強化	新規製品開発	コンプライアンス	在庫圧縮	ビジネスモデル変革	組織再編	意思決定迅速化	市場環境対応	グローバル化	サプライチェーンの最適化	環境対策	その他の経営課題		利益改善	生産性向上	顧客満足度向上	従業員満足度向上	新規ビジネス	シェア拡大	その他の評価指標		イノベーション	新規顧客獲得	社外デバイスデータ利用	社内デバイスデータ利用	ネットワークデータ利用	デバイスデータセキュリティ	業務システム統合		モノのインターネット (IoT)	ビッグデータ	ビジネス・インテリジェンス	クラウド・サービス	モバイル・テクノロジ	ソーシャル・メディア	ロケーション・インテリジェンス	3Dプリンティング	スマートマシン		多言語対応					Discovery	Assignment	Solution	Inspection	Consent	Action			AI	RPA	機械学習	技術技能伝承	BA	HRM/HCM	共創	デザインシンキング	オープンイノベーション	地方創成	地域活性化	働き方改革".split(TAB)






keywords = {}


src.lines.each do |line|
  fields = line.chop.split(TAB)
  cust = fields.shift
  url = fields.shift
  ix = fields.each_with_index.select{|e,i| e != ""}.map{|a|a.last+2}
  arr = KEYWORDS.values_at(*ix)
  arr.each do |kw|
    keywords[kw]||=[]
    keywords[kw] << url
  end
end

keywords.each do |k,a|
  a.each do |u|
    puts [k,u].join(TAB)
  end
end


#エースコックベトナム社 様	www.fujitsu.com/jp/about/resources/case-studies/cs-201705-acecook.html

